const apiURL = 'https://seashell-app-bqaqe.ondigitalocean.app'

/**
 * transforms json to facts usable in front
 * @param {JSON} json 
 * @returns {{id: number, text: string, isTrue: boolean, explaination: string, trueProportion: number, falseProportion: number}}
 */
const jsonToFacts = (json) => {
    return {
        id: json.id,
        text: json.intitule,
        isTrue: json.isVraie,
        explaination: json.explication,
        trueProportion: json.nbVoteVrai/(json.nbVoteVrai+json.nbVoteFaux),
        falseProportion: json.nbVoteFaux/(json.nbVoteVrai+json.nbVoteFaux)
    }
}

const FetchFacts = async () => {
    try {
        const response = await fetch(apiURL + "/questions", {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Origin': window.location.origin
            }
        });

        if(response.ok) {
            const json = await response.json();
            return json.map((elem) => jsonToFacts(elem));
        } else {
            const message = await response.text() + "\n(generated by FetchFacts)";
            return Promise.reject({status: response.status,statusText: message});
        }
    } catch (error) {
        console.warn(error.message);
        return Promise.reject({status: 500,statusText: "Server error" + "\n(generated by FetchFacts)"});
    }
}